spring.application.name=educacional
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=654321

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

firebase.api.key=AIzaSyDMKols4cS7X3MVPUd56gzNYxi7cTxhFQ8
firebase.auth.domain=toserveyou-3d997.firebaseapp.com
firebase.project.id=toserveyou-3d997
firebase.storage.bucket=toserveyou-3d997.firebasestorage.app
firebase.messaging.sender.id=956647011856
firebase.app.id=1:956647011856:web:864ee8b4d9828011bfbc95